#!/bin/sh
###############################
# Copyright (C) 2012/2013 shibby
# Changes for new versioning: 2018 - 2021 by pedro
# Changes for new versioning: 2018 - 2021 by pedro
# Changes for FreshTomato AX branch 2023
#
# This script send anonymous or incompleted information about model of router and installed tomato version.
# Those information will be used ONLY for stats.
# Any of private information will be NOT sended!
# Results you can explore on http://anon.groov.pl page.
# If you don`t agree to run this script you can disable it in GUI.
#
# Sended information:
# - MD5SUM of WAN+LAN MAC addresses - this will identify a router. Ex: 1c1dbd4202d794251ec1acf1211bb2c8
# - Model of router. Ex: Asus TUF-AX3000
# - Version of installed tomato. Ex: 2023.3
# - Builtype. Ex: K419ARM
# - Uptime of your router. Ex: 7 days
# - Number of version for tomato update notification system. Ex: 2023.4
#
# That`s all
###############################

ANON_ENABLED=$(nvram get tomatoanon_enable)
ANON_ANSWER=$(nvram get tomatoanon_answer)
ANON_NOTIFY=$(nvram get tomatoanon_notify)
WGET="wget"
WGET_OPT="-t 2 -T 15 --no-check-certificate"
RESULT="/tmp/anon.result"
RESULTVER="/tmp/anon.version"
WGET_RESULT=0

# Mod, Version and Buildtyp
MOD=FreshTomato
VER=$(nvram get os_version | awk '{ print $1" "$(NF-2)" "$(NF-1) }')
BUILDTYPE=$(nvram get os_version | awk '{ print $NF }')

# Collect data for TomatoAnon database
UPTIME=$(uptime | cut -d "," -f1 | cut -d " " -f4,5)
WANMAC=$(nvram get wan_hwaddr)
LANMAC=$(nvram get lan_hwaddr)
MODEL=$(nvram get t_model_name)
DRIVER=$(wl ver | grep version | awk '{ print $7 }')
WANMAC_MD5=$(echo "$WANMAC+$LANMAC" | md5sum | awk '{ print $1 }')
ROUTERID=$(nvram get tomatoanon_id)

# TomatoAnon Database update
if [ "$ANON_ENABLED" == "1" -a "$ANON_ANSWER" == "1" ]; then

	# Check and save anon id if needed
	[ ! "$ROUTERID" == "$WANMAC_MD5" ] && {
		nvram set tomatoanon_id="$WANMAC_MD5"
		nvram commit
	}

	# Change all spaces to %20.
	ANONSEND=$(echo "http://anon.groov.pl/index.php?wanmac_md5=$WANMAC_MD5&model=$MODEL&version=$VER&buildtype=$BUILDTYPE&driver=$DRIVER&uptime=$UPTIME&mod=$MOD&anon=1" | sed "s/ /%20/g")

	# We have all we need and we can send data to Anon database
	$WGET $WGET_OPT -O $RESULT $ANONSEND
	WGET_RESULT=$?
	if [ "$WGET_RESULT" != "0" ]; then
		logger "TomatoAnon - update Database failed!"
	else
		logger "TomatoAnon - update Database successful"
	fi

	# Thanks. Now add cron job
	ISCRU=$(cru l | grep anonupdate | wc -l)
	[ "$ISCRU" -eq 0 ] && {
		# random minutes 0..59
		MINUTES=$(awk 'BEGIN {srand(); printf "%d", 60*rand()}')

		# random hour 0..23
		HOUR=$(awk 'BEGIN {srand(); printf "%d", 23*rand()}')

		# random day of week 0..6
		DAY=$(awk 'BEGIN {srand(); printf "%d", 6*rand()}')

		# update anon one time per week
		cru a anonupdate "$MINUTES $HOUR * * $DAY tomatoanon -start"
	}
fi

# FreshTomato Update Notification
if [ "$ANON_ENABLED" == "1" -a "$ANON_ANSWER" == "1" -a "$ANON_NOTIFY" == "1" ]; then
	# ToDo :)
fi
